### ISSUE TITLE
cocoapods can't use 2.2 version 

### ISSUE THREAD

**Issue by threeknife** [magicalpanda/MagicalRecord#1037]
[!] The platform of the target `Leo` (iOS 6.0) is not compatible with `MagicalRecord (2.3.0)` which has a minimum requirement of iOS 6.1 - OS X 10.8.

**Comment by tonyarnold** [comment]
You're targeting iOS 6.0. The minimum version that we support in MagicalRecord 2.3 is iOS 6.1.

**Comment by ipodishima** [comment]
Why the hell did you dropped support for 2.2 on cocoapods? I have to update several dependencies relying on this version because of this

**Comment by Alydyn** [comment]
@ipodishima nice language.  You're right, we should just keep using 2.2 into perpetuity and never improve MR.

**Comment by ipodishima** [comment]
Well,

First of all, I wasn't trying to insult anyone or abuse language.

I'm not asking not to improve MR. 
Not every projects I'm working on can be updated like it for several reasons. First which comes in mind is that I have to migrate sensitive code related to MagicalRecord and database handling without creating regressions.
This is simply not possible for some projects because the version of MR is stable enough for me to use it. I see no reasons forcing me to upgrade.
I'll definitively use 2.3 on next versions, but please let us perform a pod install using 2.2 version. This is up to us to migrate to newer versions and not bother you with support on oldest versions. But in my opinion, you cannot force us to migrate.
Take facebook for exemple, there are changing several things at each iteration, but we still can pod install with an older version.

**Comment by waltermvp** [comment]
@ipodishima  Facebook has 50 *paid* engineers working on the news feed section of the iOS app.

**Comment by shouze** [comment]
@waltermvp I guess thei're not working but reading the news of the feed ;)

As it was working... why dropping this version in pods? In can deprecate it this way developers have more time to upgrade.

**Comment by ipodishima** [comment]
Well well well.

Before going nuts with this conversation, I think cocoapods dropped support at some point for a specific pod version specifier, which would be the reason why cocoapods is ignoring the version I'm passing to it

Sorry about that

**Comment by joejcon1** [comment]
This may be relevant https://github.com/magicalpanda/MagicalRecord/issues/1023
+1 for politeness towards maintainers

**Comment by Alexs1987** [comment]
`pod 'MagicalRecord', '2.2.0'` works for me
