### ISSUE TITLE
Watch OS 2 support

### ISSUE THREAD

**Issue by rounak** [magicalpanda/MagicalRecord#1076]
I tried adding watch os 2 to the podspec, but because iCloud isn't present on the watch, it turns up this error: `Use of undeclared identifier 'NSPersistentStoreDidImportUbiquitousContentChangesNotification'`.

AFNetworking has used ifdefs like these:

```
#if TARGET_OS_IOS
#import <UIKit/UIKit.h>
#elif TARGET_OS_WATCH
#import <WatchKit/WatchKit.h>
#endif
```

to add conditional blocks of code specific to either platform, maybe something similar could be done, so as to wrap iCloud methods in `#if TARGET_OS_IOS`

**Comment by Coeur** [comment]
Don't forget about tvOS support (Xcode 7.1 beta). ;)

**Comment by deeje** [comment]
+1 for tvOS

**Comment by invoodoo** [comment]
+1 for watchos

**Comment by jordanbigel** [comment]
Another +1 for tvOS - PLEASE!

**Comment by aalogv** [comment]
+1 for tvos

**Comment by paoloandrea** [comment]
tvOS +1

**Comment by miradesne** [comment]
+1 for watchOS

**Comment by prvyas** [comment]
+1 tvOS

**Comment by prvyas** [comment]
+1 tvOS

**Comment by fabiopalm** [comment]
+1 watchOS

**Comment by razvan-paul** [comment]
+1 watchOS

**Comment by ysoftware** [comment]
+1 watchOS

**Comment by jordanbigel** [comment]
I'm starting to worry - its been a year since people here started asking for a watchOS and tvOS version, and nothing. A year. Meanwhile, in April I took the current version and made some relatively minor tweaks - I had to disable one feature which I could not port and which I do not need (cant remember what) - but really, not much effort. And here were are a year later without an official version for tvOS. Like I said, I'm starting to worry about the future, I've got 3 production Apps in the appStore all built with MR, and I am about the release a tvOS app with a kludged version of MR - is there even a future for MR if the product is not being updated regularly?

Please explain what the issues are which have prevented MR from releasing a tvOS compatible version? Thanks.

**Comment by deeje** [comment]
Remember that this is open source.  it's all communal effort. Feel free to submit a pull request of your changes.

Types wit my thumms

**Comment by Coeur** [comment]
I've added watchOS and tvOS support on master branch / MagicalRecord 2.4.0.
