### ISSUE TITLE
iOS8 Extension issue.

### ISSUE THREAD

**Issue by muzammil-triffort** [magicalpanda/MagicalRecord#858]
When i am trying to add custom keyboard in iOS8 through AppExtension. I am unable to get database records from coredata file. Getting error : Failed to inherit CoreMedia permissions from #####. Please let me know if this is a known issue and you are working on this.

Thank you in advance.

**Comment by VAlexander** [comment]
Hi @tonyarnold  sorry to bring this post back up, but where exactly should we be using ```- (NSPersistentStore *) MR_addAutoMigratingSqliteStoreAtURL:(NSURL *)storeURL```

**Comment by flipchen** [comment]
Hello @tonyarnold, when can we expect the release of 2.3? I'm waiting for a while for it to be released now and actually need to make extensions work with CoreData quite soon.

**Comment by tonyarnold** [comment]
@flipchen honestly? I don't know. 

I could use help getting over the line, if anyone has time to contribute. 

I have two open issues, but no time to handle them properly. What's in the `develop` branch passes the basic test suite, but doesn't pass when Core Data concurrency debugging is enabled. 

Personally, I'm pretty happy with where 2.3 is at, but I'm not writing any Core Data apps right now, so I'm concerned I've missed things.

**Comment by Alydyn** [comment]
@tonyarnold where is it failing concurrency?

**Comment by tonyarnold** [comment]
@Alydyn it's not now. Just a couple of mishandled dispatches in the test suite.

**Comment by Alydyn** [comment]
Ahh okay.  Had me curious as I am using it extensively and have no issues, after fixing the working name and the persistent store lock.

**Comment by VAlexander** [comment]
@flipchen what type of extension are you trying to get to communicate with Core Data? I'm running the current 2.3 beta release and things are working spot on for my keyboard extension.

If you're using cocoa pods, simply add the following to your podfile to test it out:
``` ruby
pod "MagicalRecord", :git => 'https://github.com/magicalpanda/MagicalRecord.git', :branch => 'develop'
```

P.S. thanks for all the great work @tonyarnold  :+1:

**Comment by SandeepKrGupta** [comment]
I have added MagicalRecord in common  framework(used for both, App and  watchkit extension). I have setup core data stack in App delegate of App. App is working fine when I run app. But when I run watchkit extension.  Should i also need to setup same core data stack in InterfaceController.m file  of WatchKit Extension? 

WatchKit Extension[10143:164171] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Default context is nil! Did you forget to initialize the Core Data Stack?'


Any help would be appreciated.
Thanks
