### ISSUE TITLE
Best Practice for Importing Large Amounts of Objects?

### ISSUE THREAD

**Issue by VAlexander** [magicalpanda/MagicalRecord#937]
I have a pretty huge text file that I organize into an array of strings that are single words (~1.2 million). Many are repeats (About 29,000 unique words).

I've been trying several things, but no matter what I do performance is horrible. What's the best way of importing this amount of data into core data using MagicalRecord? Currently I'm doing the following, but it literally takes over an hour in the simulator.

I have a method that makes use of fast enumeration as it goes through each word in the array. The method then checks if the word exists or not within core data.

If it doesn't exist I do the following:

    [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
        WordSuggestion *wordSuggestion = [WordSuggestion MR_createEntity];
        wordSuggestion.word = currentWord.lowercaseString;
        wordSuggestion.popularity = 1;
    } completion:^(BOOL success, NSError *error) {}];
======

if it does exist I do the following:

    [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
        //Word already exists so just increment the count
        WordSuggestion *wordSuggestion = [WordSuggestion MR_findFirstByAttribute:@"word" withValue:currentWord.lowercaseString inContext:localContext];
        wordSuggestion.popularity += 1;
    } completion:^(BOOL success, NSError *error) {}];

Is there a way I can create / update each object and just save once, when everything is done, rather than save each object as I iterate through the array?

**Comment by skyylex** [comment]
As you know MR use hierarchy of contexts. First level context is connected to DB file, this context is called rootSavingContext. All savings to file systen in MR are done through this context. Root context has child contexts. And saving to DB is performed using chain of save method calls. For ex. BackgroundContext->defaultContext->rootSavingContext. For huge amounts saving with root context each time will be extremely slow, because root save changes in a file ( It's the same as saving file 1 million times). That's why you need to save only current context ( NSManagedContext saveOnlySelfAndWait) for each object changes to it's parent context and after that save root context only once. In other words, you need to save all objects to root saving context and when all objects will appear in root - save root context. Saving child context is fast because is done in memory.

**Comment by VAlexander** [comment]
Ahh. Perfect explanation. Appreciate it, didn't really think of it this way. :+1:
