### ISSUE TITLE
 Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Stat 0xd5cfbf0> valueForUndefinedKey:]: the entity (null) is not key value coding-compliant for the key "updatedAt".'

### ISSUE THREAD

**Issue by KiuShuo** [magicalpanda/MagicalRecord#947]

**Comment by tonyarnold** [comment]
Sorry, but you're going to need to provide a lot more detail before anyone can help you with this problem. Given that it doesn't appear to be specific to MagicalRecord, you should ask your question on [Stack Overflow](http://stackoverflow.com/).

**Comment by webhive** [comment]
Got the same issue with MR_importFromObject method. I am loading entity from JSON string. First call of MR_importFromObject work fine, but on second call got:

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Booking 0x7fcd7e04d250> valueForUndefinedKey:]: the entity Booking is not key value coding-compliant for the key "(null)".'
