### ISSUE TITLE
12h/24h time format

### ISSUE THREAD

**Issue by torcelly** [magicalpanda/MagicalRecord#964]
Hi, If your device has 12h. time format and you try to parse a date with custom format like "yyyy-MM-dd'T'HH:mm:ssZZZ", it fail. It isn't a bug in MagicalRecord, it's a system issue (https://developer.apple.com/library/mac/qa/qa1480/_index.html).

The problem can be fixed if you apply NSLocale (en_US_POSIX). However MagicalRecords doesn't allow me apply NSLocale in the userInfo and it would be very useful. Could you allow apply custom NSLocale via userInfo?

Thanks

**Comment by tonyarnold** [comment]
Hi @torcelly — reckon you could show me how that would look and I'll see what I can do?

**Comment by DanielC1272** [comment]
Is there any chance to fix this bug ?? All you need to do is change NSLocal inside MR_dateFromString function from [NSLocale currentLocale] to [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"]. That's because when you're working with fixed-format dates, you should set the locale of the date formatter to something appropriate for your fixed format. In most cases the best locale to choose is "en_US_POSIX".

You can find more information about this under the link posted by @torcelly

**Comment by nucauthu** [comment]
Any update on this ? I have run into the similar problem. I can't parse "2016-07-11T03:00:00" and "2016-07-05T04:54:06.030" with the same dateformat string.

**Comment by Coeur** [comment]
Fixed in https://github.com/magicalpanda/MagicalRecord/tree/fix/unversalDateFormat. Will pull request later.
