### ISSUE TITLE
Magical record cocoapod version?

### ISSUE THREAD

**Issue by pavm035** [magicalpanda/MagicalRecord#981]
Hi,

I'm really impressed with MR, since it saves our time like anything.
Would you please help me to get the latest MR using cocoa pod, but currently it comes with 2.2 version, but i see few branches here , master, release3.0 etc... I also noticed you mentioned about 2.3 as well, but not sure how to pull that using cocoa pod and related documentation would be really helpful

**Comment by thomassnielsen** [comment]
This will give you 2.3:
`pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :tag => 'v2.3.0-beta.5'`

**Comment by silvaricPresent** [comment]
Why not "release3.0"? 
Ok, is in development and also there is a lack of documentation but why not start from here?

**Comment by Alydyn** [comment]
3.0 isn't quite ready for release, and it is also a big change from the 2.xx versions.  If you are using in a shipping app it's probably best to stick with 2.3

**Comment by pavm035** [comment]
Thanks all, Alydyn  if i use cocoa pod it comes with 2.2, is it because cocoa pod not updated to 2.3 version? or am i missing something?

**Comment by Alydyn** [comment]
I believe it is because 2.2 is what is in the master branch.  2.3 is develop and hasn't been merged/finalized yet.  
Not 100% on that though as I don't use CocoaPods. :)

**Comment by esetnik** [comment]
+1. I think pre-release versions should also be distributed via cocoapods so that developers can easily test for breaking changes and keep up to date with the latest release candidate. With cocoapods it's easy to publish unstable builds using semantic versioning.

From [Making a Cocoapod](http://guides.cocoapods.org/making/making-a-cocoapod.html):
"Following the pattern established in RubyGems, pre-release versions can also be specified in CocoaPods. A pre-release of version 1.2, for example, can be specified by 1.2-beta3. In this example, the dependency specifier ~> 1.2-beta will match 1.2-beta3."

**Comment by pavm035** [comment]
Thanks, will wait for 2.3 or 3.0 as official release from cocoa pods,

**Comment by Coeur** [comment]
For latest 2.x release:

    pod 'MagicalRecord', '~> 2.3'

For latest master branch:

    pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :branch => 'master'
